// Main client

export { BookingClient } from "./client/booking.js";
export { MasterRecordsClient } from "./client/master-records.js";
export {
	AvesOp,
	AvesOpSchema,
	type OpParams,
	type OpResult,
} from "./client/ops.js";
export { PackageCatalogClient } from "./client/packages.js";
export { AvesTransport } from "./client/transport.js";
export {
	AvesClient,
	type AvesClientDeps,
} from "./client.js";
export { AvesError } from "./error.js";

// Shared object enums (+ Valibot schemas)
export {
	AvesSearchType,
	AvesSearchTypeSchema,
	AvesServiceType,
	AvesServiceTypeSchema,
	BookedServiceStatus,
	BookedServiceStatusSchema,
	BookingFileStatus,
	BookingFileStatusSchema,
	BookingFileStatusWire,
	BookingFileStatusWireSchema,
	CancelOperationType,
	CancelOperationTypeSchema,
	CarrierType,
	CarrierTypeSchema,
	CommissionIncomeType,
	CommissionIncomeTypeSchema,
	CommissionOwedType,
	CommissionOwedTypeSchema,
	CostPriceType,
	CostPriceTypeSchema,
	CustomerPaymentType,
	CustomerPaymentTypeSchema,
	DeadlineStatus,
	DeadlineStatusSchema,
	DestinationType,
	DestinationTypeSchema,
	DocumentType,
	DocumentTypeSchema,
	ExportType,
	ExportTypeSchema,
	FilePaymentOperationType,
	FilePaymentOperationTypeSchema,
	Gender,
	GenderSchema,
	GroupingPaxPolicy,
	GroupingPaxPolicySchema,
	InsertCriteria,
	InsertCriteriaSchema,
	MakeDocumentTo,
	MakeDocumentToSchema,
	MasterPaymentType,
	MasterPaymentTypeSchema,
	OpBodyKey,
	OpBodyKeySchema,
	OptionedExpirePolicy,
	OptionedExpirePolicySchema,
	PassengerCategory,
	PassengerCategorySchema,
	PaxQtyCriteria,
	PaxQtyCriteriaSchema,
	PaymentType,
	PaymentTypeSchema,
	Printable,
	PrintableSchema,
	PrintType,
	PrintTypeSchema,
	RecordStatus,
	RecordStatusSchema,
	RecordType,
	RecordTypeSchema,
	RecordTypeWire,
	RecordTypeWireSchema,
	RsStatusValue,
	RsStatusValueSchema,
	SearchBookingFileType,
	SearchBookingFileTypeSchema,
	SearchMasterType,
	SearchMasterTypeSchema,
	SellingType,
	SellingTypeSchema,
	ServiceRefType,
	ServiceRefTypeSchema,
	SetFileStatusValue,
	SetFileStatusValueSchema,
	StatisticType,
	StatisticTypeSchema,
	Territoriality,
	TerritorialitySchema,
	ToServiceType,
	ToServiceTypeSchema,
	ToSubServiceType,
	ToSubServiceTypeSchema,
	TypeDownloadFile,
	TypeDownloadFileSchema,
} from "./schemas/enums.js";

// Types
export type {
	AccountPolicies,
	AvesClientOptions,
	AvesSearchRQ,
	Booking,
	BookingCancelInput,
	BookingExportInput,
	BookingExportResult,
	BookingFileDetailRS,
	// Booking file (CreateBookingFile + ops)
	BookingFileRQ,
	BookingFileRS,
	BookingHeaderInput,
	BookingInput,
	BookingSearchInput,
	BookingSearchResult,
	BookingStatusInput,
	BookingStatusOnlyRS,
	CancelFileRQ,
	CatalogSearchInput,
	CommitInput,
	CommitPackageRQ,
	CommitPackageRS,
	DynamicFields,
	// Booking export (ExportBookingData)
	ExportBookingDataRQ,
	ExportBookingDataRS,
	ExportExtraInfo,
	ExportedBookingFile,
	FilePaymentListRQ,
	// Master record types
	FinancialDetail,
	IdDocumentDetail,
	// Upsert types
	ManageMasterRecordRequest,
	ManageMasterRecordRS,
	MasterRecord,
	MasterRecordDetail,
	MasterRecordDetailResponse,
	MasterRecordInput,
	MasterSearchInput,
	MasterSearchResult,
	ModFileHeaderRQ,
	ModFileServicesRQ,
	OperationStatus,
	Package,
	PackageDetailRQ,
	PackageDetailRS,
	PackageInput,
	PackageSearchResult,
	PaymentInput,
	RqHeader,
	RsStatus,
	SearchBookingFileRQ,
	SearchBookingFileRS,
	// Search types
	SearchMasterRecord,
	SearchMasterRecordRS,
	SearchPackageRS,
	SearchServicesRS,
	ServiceSearchResult,
	ServiceStatusInput,
	ServiceUpdateInput,
	SetFileServiceStatusRQ,
	SetFileStatusRQ,
} from "./types.js";
